apiVersion: v1
data:
  DATABASE_NAME: todo
  DATABASE_PASSWORD: redhat123
  DATABASE_SVC_HOSTNAME: tododb
  DATABASE_USER: todoapp
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 20d773370efdfce3221f56348ba2c544558a58a3
    fabric8.io/git-branch: todo-migrate
    fabric8.io/git-url: https://github.com/tavorserenase/DO288-apps
  labels:
    app: todo-api
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: com.redhat.training.example
  name: todoapi
  namespace: archibaldtuttlebuttle-todo-migrate
